# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Slownik Rymow' do
pod 'Alamofire', '~> 4.0'
end

target 'Slownik RymowTests' do

end